spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 1234
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
        default-requeue-rejected: false

application:
  name: MessageQueue

server:
  port: 8080